@startuml
'https://plantuml.com/activity-diagram-beta

start
:客户端实例化NamingService实现类，调用register方法;
:通过一系列重载方法，最终生成Instance实例对象，集群默认为“DEFAULT”、分组默认为“DEFAULT_GROUP”、权重默认为1.0;
:NamingClientProxyDelegate实例进行注册（委派模式）;
if (Instance实例是)
stop

@enduml
