@startuml
'https://plantuml.com/activity-diagram-beta

|发起节点|
start
:DistroClientDataProcessor监听ClientEvent.ClientChangedEvent事件;
:构造Distro数据包，设置action为“CHANGE”;
:遍历节点列表，向每个节点异步发送Distro数据包;
|发起节点|

|#AntiqueWhite|接收节点|
:DistroDataRequestHandler接收Distro相关请求;
:解析Distro数据包，更新节点的注册表数据;
|接收节点|

stop

@enduml
